### ISSUE TITLE
Fix up incomplete prefixes

### ISSUE THREAD

**Issue by hamishwillee** [WICG/responsive-image-client-hints#13]
There are a couple of places where the spec does not use the full prefix. This is a little ambiguous, because it is in theory possible that in the cases below you do actually mean you can omit the `SEC-` or `SEC-CH-` prefixes.

Examples - there might be more (search on these)
- Vary: DPR
- Accept-CH: CH-DPR, CH-Width

**Comment by eeeps** [comment]
Yes! Oops! I'll fix this up with a PR shortly...

**Comment by hamishwillee** [comment]
Thanks very much!
