### ISSUE TITLE
Possible to add an audit trail back to the original spec/messages?

### ISSUE THREAD

**Issue by hamishwillee** [WICG/responsive-image-client-hints#15]
When I was documenting Content-DPR, DPR, Viewport-Width etc for MDN they were documented in [draft 6](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-client-hints-06) and in draft 7 there was a mention that they had been removed and would be documented in a new spec.

Because these were renamed, the new spec did not show up on search - effectively the audit trail of what happened with these messages was broken. Had to be restored by finding you guys on WHATWG.

Would be great if this is possible to work out without having to know about the WHATWG or ask questions like https://github.com/WICG/responsive-image-client-hints/issues/14.

Maybe a note in the old spec, or something in this spec to highlight the move for search. I will certainly be creating such a trail in MDN docs.

**Comment by eeeps** [comment]
The "Previous Versions" section of the front matter to the spec links to: https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-client-hints-06#section-3

That helps you get from here, to draft 6 (the last IETF Client Hints draft that defined these hints).

Are you asking from a path from draft 6 or 7, to here? I don't think that'll be possible.
Or a note in the current IETF draft, explaining the removal and pointing here?
Or a note here explaining the history and how things have forked (it is a bit of a long and confusing tale...)?

**Comment by hamishwillee** [comment]
Probably what would have helped me most is the thing you say is not possible :-) : "Are you asking from a path from draft 6 or 7, to here?".

The next best thing is a better result on search for any of the _old_ headers that highlights the responsive header spec. That would be enough for me to find the new spec and draw the connection. I don't know how to achieve that, and I suspect in a year it will have happened by magic. 

Sorry I can't give you a solution, but I hope that the problem is at least clear and obvious.

**Comment by eeeps** [comment]
It is! Perhaps the best solution for most people though, will be updates to the relevant MDN articles (:

**Comment by hamishwillee** [comment]
Fair enough! Feel free to close this. FYI trigger for MDN work will be support in chromium based browsers. After that happens the browser compatibility data will be updated, and MDN docs should follow soon after.

**Comment by yoavweiss** [comment]
^^ @miketaylr
