### ISSUE TITLE
Add explainer for Viewport Height Client Hint

### ISSUE THREAD

**Issue by tarunban** [WICG/responsive-image-client-hints#6]
This was briefly discussed in https://discourse.wicg.io/t/viewport-height-client-hint-proposal/4993. I believe this is the right repo for adding the explainer as the main motivation of the new client hint is for origins to serve responsive images.

**Comment by tarunban** [comment]
Also, /cc @yoavweiss

**Comment by eeeps** [comment]
Closed via #7

**Comment by tarunban** [comment]
Thanks @eeeps for the merges!
