### ISSUE TITLE
Meta: switch GH Pages branch to enable auto build/deploys

### ISSUE THREAD

**Issue by eeeps** [WICG/responsive-image-client-hints#9]
I spent a little time getting https://github.com/w3c/spec-prod set up, here, today. But I couldn't figure out a way to get it to build and deploy to `master`. So I set up a `gh-pages` branch; @yoavweiss can you switch the repo's GH source branch over, so that that's what's published on https://wicg.github.io/responsive-image-client-hints ?

**Comment by yoavweiss** [comment]
Done!
